# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c344e8f5cc547253c4b92417b9ba8dad994cf8db17e38aabbe494e83f935d7df7dee715d4f12f5f9d05613efe143a338be1ebc11a6b29d45a36e76a2e805b80f

test:
  secret_key_base: ae05c50586cc012c953c8358db16e93d9140b9326ab36f6f9a8c6c89713baa4863894870efcc958d7d56261cae40bb0497adf90e8ef7ddcabab58c28a3ff28dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
