# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85dcac9c325ff08fcb7b1206e2508027fab2073ed457207589e1f17d4606b447faccdf0c64dd9244e625e844a29421326da22821f2202514330c3359aea0be73

test:
  secret_key_base: e6b6490ff15e0540410bf3a8bd477fdfe1c8032ace55a271332a7a4e253d3247f9f2c6e05dd03ff0962c541ef0472b14bedaa0f9a77b90f3e51a5d2e402e6bb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
