# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c0cae746bf8a92e36124f504be9b1df5fa1ffc3c372fdb21990690367902c3c8b28d949982871a3609b02c1a6a8cd6ab086a6a98284d4a4b08b6f5a552bde5e

test:
  secret_key_base: 7c351119baa0bd1326572c43f6bd1dc02a84ef48de0af07fb441e1332fa57154823fe2ba85bb083334b6afff30daf7d539ba421da426c4ebeeabcda8b4572191

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
