# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a07ba7d1649b4ed89f6e2904ad72c125224c3a6252a55d777bc275f55fd6c1cde123456c755790d2fd67edbd0186214aeac108da42f90cd884c667fdd3b7b02

test:
  secret_key_base: 55197bd79d7095f0f5b4d1402973b35dd91bfab2ca618fc89fd470a91ff9651fe91df8651f059e6f57640b73a5eed862d3deb227000c6a89747c9bbab8635ea3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
