# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d0cf65a4a18d144b0b914534c99b7b50008d1836c5e9064854707884316b46f589eb2ebbdd5f870008168224f6842954b6f699f582ae534eba7b8f2f1d74496

test:
  secret_key_base: 1e1f72830a0aca37d9b7cde31d39d2b38f9e1b7456c112f3a2699016c33d55b37bd5218ea7ea194cc28b644ac296b46428ae34b9c709325d00f44eeaf06ec75c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
