# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a33d65e184835957504d6598a72b4b580e40edc0d93e0c0e5ac6e78c6ca3c8270625e02003adefa90e6dc1e8de349b1176e82ce2ec9d474f12b48cf8ef5d852

test:
  secret_key_base: ab7dd9c71bff98e46051cb0c0b6724a47213636e76c5914d8af5780a7da5726537bef685a2f1c2cb33c38a71f11b88ece82b43f1511c13e5ea8fadc546e08e17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
